<script setup>
const surahList = [
  {
    id: 1,
    revelationPlace: 'Mekke',
    bismillahPre: true,
    nameSimple: 'Fâtiha Suresi',
    nameArabic: 'سُورَةُ الفَاتِحَة',
    versesCount: 7,
    audioUrl: 'https://tevhidmeali.com/assets/mp3/ar/sure/abdussamed/001.mp3',
  },
  {
    id: 2,
    revelationPlace: 'Medine',
    bismillahPre: true,
    nameSimple: 'Bakara Suresi',
    nameArabic: 'سُورَةُ البَقَرَة',
    versesCount: 286,
    audioUrl: 'https://tevhidmeali.com/assets/mp3/ar/sure/abdussamed/002.mp3',
  },
  {
    id: 3,
    revelationPlace: 'Medine',
    bismillahPre: true,
    nameSimple: 'Âl-i İmrân Suresi',
    nameArabic: 'سُورَةُ آل عِمرَان',
    versesCount: 200,
    audioUrl: 'https://tevhidmeali.com/assets/mp3/ar/sure/abdussamed/003.mp3',
  },
  {
    id: 4,
    revelationPlace: 'Medine',
    bismillahPre: true,
    nameSimple: 'Nisâ Suresi',
    nameArabic: 'سُورَةُ النِّسَاء',
    versesCount: 176,
    audioUrl: 'https://tevhidmeali.com/assets/mp3/ar/sure/abdussamed/004.mp3',
  },
  {
    id: 5,
    revelationPlace: 'Medine',
    bismillahPre: true,
    nameSimple: 'Mâide Suresi',
    nameArabic: 'سُورَةُ المَائدة',
    versesCount: 120,
    audioUrl: 'https://tevhidmeali.com/assets/mp3/ar/sure/abdussamed/005.mp3',
  },
  {
    id: 6,
    revelationPlace: 'Mekke',
    bismillahPre: true,
    nameSimple: 'En’âm Suresi',
    nameArabic: 'سُورَةُ الاٴنعَام',
    versesCount: 165,
    audioUrl: 'https://tevhidmeali.com/assets/mp3/ar/sure/abdussamed/006.mp3',
  },
  {
    id: 7,
    revelationPlace: 'Mekke',
    bismillahPre: true,
    nameSimple: 'A’râf Suresi',
    nameArabic: 'سُورَةُ الاٴعرَاف',
    versesCount: 206,
    audioUrl: 'https://tevhidmeali.com/assets/mp3/ar/sure/abdussamed/007.mp3',
  },
  {
    id: 8,
    revelationPlace: 'Medine',
    bismillahPre: true,
    nameSimple: 'Enfâl Suresi',
    nameArabic: 'سُورَةُ الاٴنفَال',
    versesCount: 75,
    audioUrl: 'https://tevhidmeali.com/assets/mp3/ar/sure/abdussamed/008.mp3',
  },
  {
    id: 9,
    revelationPlace: 'Medine',
    bismillahPre: false,
    nameSimple: 'Tevbe Suresi',
    nameArabic: 'سُورَةُ التّوبَة',
    versesCount: 129,
    audioUrl: 'https://tevhidmeali.com/assets/mp3/ar/sure/abdussamed/009.mp3',
  },
  {
    id: 10,
    revelationPlace: 'Mekke',
    bismillahPre: true,
    nameSimple: 'Yûnus Suresi',
    nameArabic: 'سُورَةُ يُونس',
    versesCount: 109,
    audioUrl: 'https://tevhidmeali.com/assets/mp3/ar/sure/abdussamed/010.mp3',
  },
  {
    id: 11,
    revelationPlace: 'Mekke',
    bismillahPre: true,
    nameSimple: 'Hûd Suresi',
    nameArabic: 'سُورَةُ هُود',
    versesCount: 123,
    audioUrl: 'https://tevhidmeali.com/assets/mp3/ar/sure/abdussamed/011.mp3',
  },
  {
    id: 12,
    revelationPlace: 'Mekke',
    bismillahPre: true,
    nameSimple: 'Yûsuf Suresi',
    nameArabic: 'سُورَةُ يُوسُف',
    versesCount: 111,
    audioUrl: 'https://tevhidmeali.com/assets/mp3/ar/sure/abdussamed/012.mp3',
  },
  {
    id: 13,
    revelationPlace: 'Medine',
    bismillahPre: true,
    nameSimple: 'Ra’d Suresi',
    nameArabic: 'سُورَةُ الرّعد',
    versesCount: 43,
    audioUrl: 'https://tevhidmeali.com/assets/mp3/ar/sure/abdussamed/013.mp3',
  },
  {
    id: 14,
    revelationPlace: 'Mekke',
    bismillahPre: true,
    nameSimple: 'İbrahim Suresi',
    nameArabic: ' سُورَةُ إبراهيم',
    versesCount: 52,
    audioUrl: 'https://tevhidmeali.com/assets/mp3/ar/sure/abdussamed/014.mp3',
  },
  {
    id: 15,
    revelationPlace: 'Mekke',
    bismillahPre: true,
    nameSimple: 'Hicr Suresi',
    nameArabic: 'سُورَةُ الحِجر',
    versesCount: 99,
    audioUrl: 'https://tevhidmeali.com/assets/mp3/ar/sure/abdussamed/015.mp3',
  },
  {
    id: 16,
    revelationPlace: 'Mekke',
    bismillahPre: true,
    nameSimple: 'Nahl Suresi',
    nameArabic: 'سُورَةُ النّحل ',
    versesCount: 128,
    audioUrl: 'https://tevhidmeali.com/assets/mp3/ar/sure/abdussamed/016.mp3',
  },
  {
    id: 17,
    revelationPlace: 'Mekke',
    bismillahPre: true,
    nameSimple: 'İsrâ Suresi',
    nameArabic: 'سُورَةُ بنى اسر',
    versesCount: 111,
    audioUrl: 'https://tevhidmeali.com/assets/mp3/ar/sure/abdussamed/017.mp3',
  },
  {
    id: 18,
    revelationPlace: 'Mekke',
    bismillahPre: true,
    nameSimple: 'Kehf Suresi',
    nameArabic: 'سُورَةُ الكهف',
    versesCount: 110,
    audioUrl: 'https://tevhidmeali.com/assets/mp3/ar/sure/abdussamed/018.mp3',
  },
  {
    id: 19,
    revelationPlace: 'Mekke',
    bismillahPre: true,
    nameSimple: 'Meryem Suresi',
    nameArabic: 'سُورَةُ مَريَم',
    versesCount: 98,
    audioUrl: 'https://tevhidmeali.com/assets/mp3/ar/sure/abdussamed/019.mp3',
  },
  {
    id: 20,
    revelationPlace: 'Mekke',
    bismillahPre: true,
    nameSimple: 'Tâ-Hâ Suresi',
    nameArabic: 'سُورَةُ طٰه ',
    versesCount: 135,
    audioUrl: 'https://tevhidmeali.com/assets/mp3/ar/sure/abdussamed/020.mp3',
  },
  {
    id: 21,
    revelationPlace: 'Mekke',
    bismillahPre: true,
    nameSimple: 'Enbiyâ Suresi',
    nameArabic: 'سُورَةُ الاٴنبياء ',
    versesCount: 112,
    audioUrl: 'https://tevhidmeali.com/assets/mp3/ar/sure/abdussamed/021.mp3',
  },
  {
    id: 22,
    revelationPlace: 'Medine',
    bismillahPre: true,
    nameSimple: 'Hac Suresi',
    nameArabic: 'سُورَةُ الحَجّ',
    versesCount: 78,
    audioUrl: 'https://tevhidmeali.com/assets/mp3/ar/sure/abdussamed/022.mp3',
  },
  {
    id: 23,
    revelationPlace: 'Mekke',
    bismillahPre: true,
    nameSimple: 'Mü’minûn Suresi',
    nameArabic: 'سُورَةُ المؤمنون ',
    versesCount: 118,
    audioUrl: 'https://tevhidmeali.com/assets/mp3/ar/sure/abdussamed/023.mp3',
  },
  {
    id: 24,
    revelationPlace: 'Medine',
    bismillahPre: true,
    nameSimple: 'Nûr Suresi',
    nameArabic: 'سُورَةُ النُّور ',
    versesCount: 64,
    audioUrl: 'https://tevhidmeali.com/assets/mp3/ar/sure/abdussamed/024.mp3',
  },
  {
    id: 25,
    revelationPlace: 'Mekke',
    bismillahPre: true,
    nameSimple: 'Furkân Suresi',
    nameArabic: 'سُورَةُ الفُرقان',
    versesCount: 77,
    audioUrl: 'https://tevhidmeali.com/assets/mp3/ar/sure/abdussamed/025.mp3',
  },
  {
    id: 26,
    revelationPlace: 'Mekke',
    bismillahPre: true,
    nameSimple: 'Şu’arâ Suresi',
    nameArabic: 'سُورَةُ الشُّعَرَاء',
    versesCount: 227,
    audioUrl: 'https://tevhidmeali.com/assets/mp3/ar/sure/abdussamed/026.mp3',
  },
  {
    id: 27,
    revelationPlace: 'Mekke',
    bismillahPre: true,
    nameSimple: 'Neml Suresi',
    nameArabic: 'سُورَةُ النَّمل ',
    versesCount: 93,
    audioUrl: 'https://tevhidmeali.com/assets/mp3/ar/sure/abdussamed/027.mp3',
  },
  {
    id: 28,
    revelationPlace: 'Mekke',
    bismillahPre: true,
    nameSimple: 'Kasas Suresi',
    nameArabic: 'سُورَةُ القَصَص',
    versesCount: 88,
    audioUrl: 'https://tevhidmeali.com/assets/mp3/ar/sure/abdussamed/028.mp3',
  },
  {
    id: 29,
    revelationPlace: 'Mekke',
    bismillahPre: true,
    nameSimple: 'Ankebût Suresi',
    nameArabic: 'سُورَةُ العَنكبوت',
    versesCount: 69,
    audioUrl: 'https://tevhidmeali.com/assets/mp3/ar/sure/abdussamed/029.mp3',
  },
  {
    id: 30,
    revelationPlace: 'Mekke',
    bismillahPre: true,
    nameSimple: 'Rûm Suresi',
    nameArabic: 'سُورَةُ الرُّوم',
    versesCount: 60,
    audioUrl: 'https://tevhidmeali.com/assets/mp3/ar/sure/abdussamed/030.mp3',
  },
  {
    id: 31,
    revelationPlace: 'Mekke',
    bismillahPre: true,
    nameSimple: 'Lokman Suresi',
    nameArabic: ' سُورَةُ لقمَان',
    versesCount: 34,
    audioUrl: 'https://tevhidmeali.com/assets/mp3/ar/sure/abdussamed/031.mp3',
  },
  {
    id: 32,
    revelationPlace: 'Mekke',
    bismillahPre: true,
    nameSimple: 'Secde Suresi',
    nameArabic: 'سُورَةُ السَّجدَة',
    versesCount: 30,
    audioUrl: 'https://tevhidmeali.com/assets/mp3/ar/sure/abdussamed/032.mp3',
  },
  {
    id: 33,
    revelationPlace: 'Medine',
    bismillahPre: true,
    nameSimple: 'Ahzâb Suresi',
    nameArabic: 'سُورَةُ الاٴحزَاب ',
    versesCount: 73,
    audioUrl: 'https://tevhidmeali.com/assets/mp3/ar/sure/abdussamed/033.mp3',
  },
  {
    id: 34,
    revelationPlace: 'Mekke',
    bismillahPre: true,
    nameSimple: 'Sebe’ Suresi',
    nameArabic: 'سُورَةُ سَبَإ ',
    versesCount: 54,
    audioUrl: 'https://tevhidmeali.com/assets/mp3/ar/sure/abdussamed/034.mp3',
  },
  {
    id: 35,
    revelationPlace: 'Mekke',
    bismillahPre: true,
    nameSimple: 'Fâtır Suresi',
    nameArabic: 'سُورَةُ فَاطِر',
    versesCount: 45,
    audioUrl: 'https://tevhidmeali.com/assets/mp3/ar/sure/abdussamed/035.mp3',
  },
  {
    id: 36,
    revelationPlace: 'Mekke',
    bismillahPre: true,
    nameSimple: 'Yâsîn Suresi',
    nameArabic: 'سُورَةُ يسٓ',
    versesCount: 83,
    audioUrl: 'https://tevhidmeali.com/assets/mp3/ar/sure/abdussamed/036.mp3',
  },
  {
    id: 37,
    revelationPlace: 'Mekke',
    bismillahPre: true,
    nameSimple: 'Sâffât Suresi',
    nameArabic: 'سُورَةُ الصَّافات ',
    versesCount: 182,
    audioUrl: 'https://tevhidmeali.com/assets/mp3/ar/sure/abdussamed/037.mp3',
  },
  {
    id: 38,
    revelationPlace: 'Mekke',
    bismillahPre: true,
    nameSimple: 'Sâd Suresi',
    nameArabic: 'سُورَةُ صٓ ',
    versesCount: 88,
    audioUrl: 'https://tevhidmeali.com/assets/mp3/ar/sure/abdussamed/038.mp3',
  },
  {
    id: 39,
    revelationPlace: 'Mekke',
    bismillahPre: true,
    nameSimple: 'Zümer Suresi',
    nameArabic: 'سُورَةُ الزُّمَر',
    versesCount: 75,
    audioUrl: 'https://tevhidmeali.com/assets/mp3/ar/sure/abdussamed/039.mp3',
  },
  {
    id: 40,
    revelationPlace: 'Mekke',
    bismillahPre: true,
    nameSimple: 'Mü’min Suresi',
    nameArabic: 'سُورَةُ مؤمن / غَافر ',
    versesCount: 85,
    audioUrl: 'https://tevhidmeali.com/assets/mp3/ar/sure/abdussamed/040.mp3',
  },
  {
    id: 41,
    revelationPlace: 'Mekke',
    bismillahPre: true,
    nameSimple: 'Fussilet Suresi',
    nameArabic: 'سُورَةُ فُصّلَت ',
    versesCount: 54,
    audioUrl: 'https://tevhidmeali.com/assets/mp3/ar/sure/abdussamed/041.mp3',
  },
  {
    id: 42,
    revelationPlace: 'Mekke',
    bismillahPre: true,
    nameSimple: 'Şûrâ Suresi',
    nameArabic: 'سُورَةُ الشّورى',
    versesCount: 53,
    audioUrl: 'https://tevhidmeali.com/assets/mp3/ar/sure/abdussamed/042.mp3',
  },
  {
    id: 43,
    revelationPlace: 'Mekke',
    bismillahPre: true,
    nameSimple: 'Zuhruf Suresi',
    nameArabic: 'سُورَةُ الزّخرُف',
    versesCount: 89,
    audioUrl: 'https://tevhidmeali.com/assets/mp3/ar/sure/abdussamed/043.mp3',
  },
  {
    id: 44,
    revelationPlace: 'Mekke',
    bismillahPre: true,
    nameSimple: 'Duhân Suresi',
    nameArabic: 'سُورَةُ الدّخان',
    versesCount: 59,
    audioUrl: 'https://tevhidmeali.com/assets/mp3/ar/sure/abdussamed/044.mp3',
  },
  {
    id: 45,
    revelationPlace: 'Mekke',
    bismillahPre: true,
    nameSimple: 'Câsiye Suresi ',
    nameArabic: ' سُورَةُ الجَاثية ',
    versesCount: 37,
    audioUrl: 'https://tevhidmeali.com/assets/mp3/ar/sure/abdussamed/045.mp3',
  },
  {
    id: 46,
    revelationPlace: 'Mekke',
    bismillahPre: true,
    nameSimple: 'Ahkâf Suresi',
    nameArabic: 'سُورَةُ الاٴحقاف',
    versesCount: 35,
    audioUrl: 'https://tevhidmeali.com/assets/mp3/ar/sure/abdussamed/046.mp3',
  },
  {
    id: 47,
    revelationPlace: 'Medeni',
    bismillahPre: true,
    nameSimple: 'Muhammed Suresi',
    nameArabic: 'سُورَةُ محَمَّد ',
    versesCount: 38,
    audioUrl: 'https://tevhidmeali.com/assets/mp3/ar/sure/abdussamed/047.mp3',
  },
  {
    id: 48,
    revelationPlace: 'Medeni',
    bismillahPre: true,
    nameSimple: 'Fetih Suresi',
    nameArabic: 'سُورَةُ الفَتْح',
    versesCount: 29,
    audioUrl: 'https://tevhidmeali.com/assets/mp3/ar/sure/abdussamed/048.mp3',
  },
  {
    id: 49,
    revelationPlace: 'Medeni',
    bismillahPre: true,
    nameSimple: 'Hucurât Suresi',
    nameArabic: 'سُورَةُ الحُجرَات',
    versesCount: 18,
    audioUrl: 'https://tevhidmeali.com/assets/mp3/ar/sure/abdussamed/049.mp3',
  },
  {
    id: 50,
    revelationPlace: 'Mekke',
    bismillahPre: true,
    nameSimple: 'Kâf Suresi',
    nameArabic: 'سُورَةُ قٓ',
    versesCount: 45,
    audioUrl: 'https://tevhidmeali.com/assets/mp3/ar/sure/abdussamed/050.mp3',
  },
  {
    id: 51,
    revelationPlace: 'Mekke',
    bismillahPre: true,
    nameSimple: 'Zâriyât Suresi',
    nameArabic: 'سُورَةُ الذّاريَات ',
    versesCount: 60,
    audioUrl: 'https://tevhidmeali.com/assets/mp3/ar/sure/abdussamed/051.mp3',
  },
  {
    id: 52,
    revelationPlace: 'Mekke',
    bismillahPre: true,
    nameSimple: 'Tûr Suresi',
    nameArabic: ' سُورَةُ الطُّور',
    versesCount: 49,
    audioUrl: 'https://tevhidmeali.com/assets/mp3/ar/sure/abdussamed/052.mp3',
  },
  {
    id: 53,
    revelationPlace: 'Mekke',
    bismillahPre: true,
    nameSimple: 'Necm Suresi',
    nameArabic: 'سُورَةُ النّجْم ',
    versesCount: 62,
    audioUrl: 'https://tevhidmeali.com/assets/mp3/ar/sure/abdussamed/053.mp3',
  },
  {
    id: 54,
    revelationPlace: 'Mekke',
    bismillahPre: true,
    nameSimple: 'Kamer Suresi',
    nameArabic: 'سُورَةُ القَمَر',
    versesCount: 55,
    audioUrl: 'https://tevhidmeali.com/assets/mp3/ar/sure/abdussamed/054.mp3',
  },
  {
    id: 55,
    revelationPlace: 'Mekke',
    bismillahPre: true,
    nameSimple: 'Rahmân Suresi',
    nameArabic: 'سُورَةُ الرَّحمٰن',
    versesCount: 78,
    audioUrl: 'https://tevhidmeali.com/assets/mp3/ar/sure/abdussamed/055.mp3',
  },
  {
    id: 56,
    revelationPlace: 'Mekke',
    bismillahPre: true,
    nameSimple: 'Vâkı’a Suresi',
    nameArabic: 'سُورَةُ الواقِعَة',
    versesCount: 96,
    audioUrl: 'https://tevhidmeali.com/assets/mp3/ar/sure/abdussamed/056.mp3',
  },
  {
    id: 57,
    revelationPlace: 'Medeni',
    bismillahPre: true,
    nameSimple: 'Hadîd Suresi',
    nameArabic: 'سُورَةُ الحَديد',
    versesCount: 29,
    audioUrl: 'https://tevhidmeali.com/assets/mp3/ar/sure/abdussamed/057.mp3',
  },
  {
    id: 58,
    revelationPlace: 'Medeni',
    bismillahPre: true,
    nameSimple: 'Mücâdele Suresi',
    nameArabic: 'سُورَةُ المجَادلة ',
    versesCount: 22,
    audioUrl: 'https://tevhidmeali.com/assets/mp3/ar/sure/abdussamed/058.mp3',
  },
  {
    id: 59,
    revelationPlace: 'Medeni',
    bismillahPre: true,
    nameSimple: 'Haşr Suresi',
    nameArabic: 'سُورَةُ الحَشر ',
    versesCount: 24,
    audioUrl: 'https://tevhidmeali.com/assets/mp3/ar/sure/abdussamed/059.mp3',
  },
  {
    id: 60,
    revelationPlace: 'Medeni',
    bismillahPre: true,
    nameSimple: 'Mümtehine Suresi',
    nameArabic: ' سُورَةُ المُمتَحنَة ',
    versesCount: 13,
    audioUrl: 'https://tevhidmeali.com/assets/mp3/ar/sure/abdussamed/060.mp3',
  },
  {
    id: 61,
    revelationPlace: 'Medeni',
    bismillahPre: true,
    nameSimple: 'Saff Suresi',
    nameArabic: 'سُورَةُ الصَّف ',
    versesCount: 14,
    audioUrl: 'https://tevhidmeali.com/assets/mp3/ar/sure/abdussamed/061.mp3',
  },
  {
    id: 62,
    revelationPlace: 'Medeni',
    bismillahPre: true,
    nameSimple: 'Cum’a Suresi',
    nameArabic: 'سُورَةُ الجُمُعَة ',
    versesCount: 11,
    audioUrl: 'https://tevhidmeali.com/assets/mp3/ar/sure/abdussamed/062.mp3',
  },
  {
    id: 63,
    revelationPlace: 'Medeni',
    bismillahPre: true,
    nameSimple: 'Münâfikûn Suresi',
    nameArabic: 'سُورَةُ المنَافِقون ',
    versesCount: 11,
    audioUrl: 'https://tevhidmeali.com/assets/mp3/ar/sure/abdussamed/063.mp3',
  },
  {
    id: 64,
    revelationPlace: 'Medeni',
    bismillahPre: true,
    nameSimple: 'Teğâbun Suresi',
    nameArabic: 'سُورَةُ التّغَابُن ',
    versesCount: 18,
    audioUrl: 'https://tevhidmeali.com/assets/mp3/ar/sure/abdussamed/064.mp3',
  },
  {
    id: 65,
    revelationPlace: 'Medeni',
    bismillahPre: true,
    nameSimple: 'Talâk Suresi',
    nameArabic: 'سُورَةُ الطّلاَق',
    versesCount: 12,
    audioUrl: 'https://tevhidmeali.com/assets/mp3/ar/sure/abdussamed/065.mp3',
  },
  {
    id: 66,
    revelationPlace: 'Medeni',
    bismillahPre: true,
    nameSimple: 'Tahrîm Suresi',
    nameArabic: 'سُورَةُ التّحْريم',
    versesCount: 12,
    audioUrl: 'https://tevhidmeali.com/assets/mp3/ar/sure/abdussamed/066.mp3',
  },
  {
    id: 67,
    revelationPlace: 'Mekke',
    bismillahPre: true,
    nameSimple: 'Mülk Suresi',
    nameArabic: 'سُورَةُ المُلك',
    versesCount: 30,
    audioUrl: 'https://tevhidmeali.com/assets/mp3/ar/sure/abdussamed/067.mp3',
  },
  {
    id: 68,
    revelationPlace: 'Mekke',
    bismillahPre: true,
    nameSimple: 'Kalem Suresi ',
    nameArabic: ' سُورَةُ القَلَم ',
    versesCount: 52,
    audioUrl: 'https://tevhidmeali.com/assets/mp3/ar/sure/abdussamed/068.mp3',
  },
  {
    id: 69,
    revelationPlace: 'Mekke',
    bismillahPre: true,
    nameSimple: 'Hâkka Suresi',
    nameArabic: 'سُورَةُ الحَاقَّة',
    versesCount: 52,
    audioUrl: 'https://tevhidmeali.com/assets/mp3/ar/sure/abdussamed/069.mp3',
  },
  {
    id: 70,
    revelationPlace: 'Mekke',
    bismillahPre: true,
    nameSimple: 'Me’âric Suresi',
    nameArabic: 'سُورَةُ المعَارج',
    versesCount: 44,
    audioUrl: 'https://tevhidmeali.com/assets/mp3/ar/sure/abdussamed/070.mp3',
  },
  {
    id: 71,
    revelationPlace: 'Mekke',
    bismillahPre: true,
    nameSimple: 'Nûh Suresi',
    nameArabic: 'سُورَةُ نُوح ',
    versesCount: 28,
    audioUrl: 'https://tevhidmeali.com/assets/mp3/ar/sure/abdussamed/071.mp3',
  },
  {
    id: 72,
    revelationPlace: 'Mekke',
    bismillahPre: true,
    nameSimple: 'Cin Suresi',
    nameArabic: 'سُورَةُ الجنّ',
    versesCount: 28,
    audioUrl: 'https://tevhidmeali.com/assets/mp3/ar/sure/abdussamed/072.mp3',
  },
  {
    id: 73,
    revelationPlace: 'Mekke',
    bismillahPre: true,
    nameSimple: 'Müzzemmil Suresi',
    nameArabic: 'سُورَةُ المُزمّل',
    versesCount: 20,
    audioUrl: 'https://tevhidmeali.com/assets/mp3/ar/sure/abdussamed/073.mp3',
  },
  {
    id: 74,
    revelationPlace: 'Mekke',
    bismillahPre: true,
    nameSimple: 'Müddessir Suresi',
    nameArabic: 'سُورَةُ المدَّثِّر',
    versesCount: 56,
    audioUrl: 'https://tevhidmeali.com/assets/mp3/ar/sure/abdussamed/074.mp3',
  },
  {
    id: 75,
    revelationPlace: 'Mekke',
    bismillahPre: true,
    nameSimple: 'Kıyâme Suresi',
    nameArabic: 'سُورَةُ القِيامَة',
    versesCount: 40,
    audioUrl: 'https://tevhidmeali.com/assets/mp3/ar/sure/abdussamed/075.mp3',
  },
  {
    id: 76,
    revelationPlace: 'Medeni',
    bismillahPre: true,
    nameSimple: 'İnsan Suresi',
    nameArabic: 'سُورَةُ دهر / الإنسَان',
    versesCount: 31,
    audioUrl: 'https://tevhidmeali.com/assets/mp3/ar/sure/abdussamed/076.mp3',
  },
  {
    id: 77,
    revelationPlace: 'Mekke',
    bismillahPre: true,
    nameSimple: 'Mürselât Suresi',
    nameArabic: 'سُورَةُ المُرسَلات',
    versesCount: 50,
    audioUrl: 'https://tevhidmeali.com/assets/mp3/ar/sure/abdussamed/077.mp3',
  },
  {
    id: 78,
    revelationPlace: 'Mekke',
    bismillahPre: true,
    nameSimple: 'Nebe’ Suresi',
    nameArabic: 'سُورَةُ النّبَإِ ',
    versesCount: 40,
    audioUrl: 'https://tevhidmeali.com/assets/mp3/ar/sure/abdussamed/078.mp3',
  },
  {
    id: 79,
    revelationPlace: 'Mekke',
    bismillahPre: true,
    nameSimple: 'Nâzi’ât Suresi',
    nameArabic: 'سُورَةُ النَّازعَات',
    versesCount: 46,
    audioUrl: 'https://tevhidmeali.com/assets/mp3/ar/sure/abdussamed/079.mp3',
  },
  {
    id: 80,
    revelationPlace: 'Mekke',
    bismillahPre: true,
    nameSimple: 'Abese Suresi',
    nameArabic: 'سُورَةُ عَبَسَ',
    versesCount: 42,
    audioUrl: 'https://tevhidmeali.com/assets/mp3/ar/sure/abdussamed/080.mp3',
  },
  {
    id: 81,
    revelationPlace: 'Mekke',
    bismillahPre: true,
    nameSimple: 'Tekvîr Suresi',
    nameArabic: 'سُورَةُ التّكوير',
    versesCount: 29,
    audioUrl: 'https://tevhidmeali.com/assets/mp3/ar/sure/abdussamed/081.mp3',
  },
  {
    id: 82,
    revelationPlace: 'Mekke',
    bismillahPre: true,
    nameSimple: 'İnfitâr Suresi',
    nameArabic: 'سُورَةُ الانفِطار',
    versesCount: 19,
    audioUrl: 'https://tevhidmeali.com/assets/mp3/ar/sure/abdussamed/082.mp3',
  },
  {
    id: 83,
    revelationPlace: 'Mekke',
    bismillahPre: true,
    nameSimple: 'Mutaffifîn Suresi ',
    nameArabic: 'سُورَةُ المطفّفِين ',
    versesCount: 36,
    audioUrl: 'https://tevhidmeali.com/assets/mp3/ar/sure/abdussamed/083.mp3',
  },
  {
    id: 84,
    revelationPlace: 'Mekke',
    bismillahPre: true,
    nameSimple: 'İnşikâk Suresi ',
    nameArabic: 'سُورَةُ الانشقاق',
    versesCount: 25,
    audioUrl: 'https://tevhidmeali.com/assets/mp3/ar/sure/abdussamed/084.mp3',
  },
  {
    id: 85,
    revelationPlace: 'Mekke',
    bismillahPre: true,
    nameSimple: 'Bürûc Suresi',
    nameArabic: 'سُورَةُ البُرُوج ',
    versesCount: 22,
    audioUrl: 'https://tevhidmeali.com/assets/mp3/ar/sure/abdussamed/085.mp3',
  },
  {
    id: 86,
    revelationPlace: 'Mekke',
    bismillahPre: true,
    nameSimple: 'Târık Suresi',
    nameArabic: 'سُورَةُ الطّارق ',
    versesCount: 17,
    audioUrl: 'https://tevhidmeali.com/assets/mp3/ar/sure/abdussamed/086.mp3',
  },
  {
    id: 87,
    revelationPlace: 'Mekke',
    bismillahPre: true,
    nameSimple: 'A’lâ Suresi',
    nameArabic: 'سُورَةُ الاٴعلى',
    versesCount: 19,
    audioUrl: 'https://tevhidmeali.com/assets/mp3/ar/sure/abdussamed/087.mp3',
  },
  {
    id: 88,
    revelationPlace: 'Mekke',
    bismillahPre: true,
    nameSimple: 'Gâşiye Suresi',
    nameArabic: 'سُورَةُ الغَاشِية ',
    versesCount: 26,
    audioUrl: 'https://tevhidmeali.com/assets/mp3/ar/sure/abdussamed/088.mp3',
  },
  {
    id: 89,
    revelationPlace: 'Mekke',
    bismillahPre: true,
    nameSimple: 'Fecr Suresi',
    nameArabic: 'سُورَةُ الفَجر',
    versesCount: 30,
    audioUrl: 'https://tevhidmeali.com/assets/mp3/ar/sure/abdussamed/089.mp3',
  },
  {
    id: 90,
    revelationPlace: 'Mekke',
    bismillahPre: true,
    nameSimple: 'Beled Suresi',
    nameArabic: 'سُورَةُ البَلَد',
    versesCount: 20,
    audioUrl: 'https://tevhidmeali.com/assets/mp3/ar/sure/abdussamed/090.mp3',
  },
  {
    id: 91,
    revelationPlace: 'Mekke',
    bismillahPre: true,
    nameSimple: 'Şems Suresi',
    nameArabic: 'سُورَةُ الشّمس ',
    versesCount: 15,
    audioUrl: 'https://tevhidmeali.com/assets/mp3/ar/sure/abdussamed/091.mp3',
  },
  {
    id: 92,
    revelationPlace: 'Mekke',
    bismillahPre: true,
    nameSimple: 'Leyl Suresi',
    nameArabic: 'سُورَةُ الليْل ',
    versesCount: 21,
    audioUrl: 'https://tevhidmeali.com/assets/mp3/ar/sure/abdussamed/092.mp3',
  },
  {
    id: 93,
    revelationPlace: 'Mekke',
    bismillahPre: true,
    nameSimple: 'Duhâ Suresi',
    nameArabic: 'سُورَةُ الضّحى ',
    versesCount: 11,
    audioUrl: 'https://tevhidmeali.com/assets/mp3/ar/sure/abdussamed/093.mp3',
  },
  {
    id: 94,
    revelationPlace: 'Mekke',
    bismillahPre: true,
    nameSimple: 'İnşirâh Suresi',
    nameArabic: 'سُورَةُ الْاِنْشِرَاحِ  ',
    versesCount: 8,
    audioUrl: 'https://tevhidmeali.com/assets/mp3/ar/sure/abdussamed/094.mp3',
  },
  {
    id: 95,
    revelationPlace: 'Mekke',
    bismillahPre: true,
    nameSimple: 'Tîn Suresi',
    nameArabic: 'سُورَةُ التِّين ',
    versesCount: 8,
    audioUrl: 'https://tevhidmeali.com/assets/mp3/ar/sure/abdussamed/095.mp3',
  },
  {
    id: 96,
    revelationPlace: 'Mekke',
    bismillahPre: true,
    nameSimple: 'Alak Suresi',
    nameArabic: 'سُورَةُ العَلق',
    versesCount: 19,
    audioUrl: 'https://tevhidmeali.com/assets/mp3/ar/sure/abdussamed/096.mp3',
  },
  {
    id: 97,
    revelationPlace: 'Mekke',
    bismillahPre: true,
    nameSimple: 'Kadr Suresi',
    nameArabic: 'سُورَةُ القَدر ',
    versesCount: 5,
    audioUrl: 'https://tevhidmeali.com/assets/mp3/ar/sure/abdussamed/097.mp3',
  },
  {
    id: 98,
    revelationPlace: 'Medeni',
    bismillahPre: true,
    nameSimple: 'Beyyine Suresi',
    nameArabic: ' سُورَةُ البَيِّنَة ',
    versesCount: 8,
    audioUrl: 'https://tevhidmeali.com/assets/mp3/ar/sure/abdussamed/098.mp3',
  },
  {
    id: 99,
    revelationPlace: 'Medeni',
    bismillahPre: true,
    nameSimple: 'Zilzâl Suresi',
    nameArabic: 'سُورَةُ الزّلزَلة ',
    versesCount: 8,
    audioUrl: 'https://tevhidmeali.com/assets/mp3/ar/sure/abdussamed/099.mp3',
  },
  {
    id: 100,
    revelationPlace: 'Mekke',
    bismillahPre: true,
    nameSimple: 'Âdiyât Suresi ',
    nameArabic: 'سُورَةُ العَاديَات ',
    versesCount: 11,
    audioUrl: 'https://tevhidmeali.com/assets/mp3/ar/sure/abdussamed/100.mp3',
  },
  {
    id: 101,
    revelationPlace: 'Mekke',
    bismillahPre: true,
    nameSimple: 'Kâri’a Suresi',
    nameArabic: 'سُورَةُ القَارعَة',
    versesCount: 11,
    audioUrl: 'https://tevhidmeali.com/assets/mp3/ar/sure/abdussamed/101.mp3',
  },
  {
    id: 102,
    revelationPlace: 'Mekke',
    bismillahPre: true,
    nameSimple: 'Tekâsür Suresi',
    nameArabic: 'سُورَةُ التّكاثُر',
    versesCount: 8,
    audioUrl: 'https://tevhidmeali.com/assets/mp3/ar/sure/abdussamed/102.mp3',
  },
  {
    id: 103,
    revelationPlace: 'Mekke',
    bismillahPre: true,
    nameSimple: 'Asr Suresi',
    nameArabic: 'سُورَةُ العَصر',
    versesCount: 3,
    audioUrl: 'https://tevhidmeali.com/assets/mp3/ar/sure/abdussamed/103.mp3',
  },
  {
    id: 104,
    revelationPlace: 'Mekke',
    bismillahPre: true,
    nameSimple: 'Hümeze Suresi',
    nameArabic: 'سُورَةُ الهُمَزة',
    versesCount: 9,
    audioUrl: 'https://tevhidmeali.com/assets/mp3/ar/sure/abdussamed/104.mp3',
  },
  {
    id: 105,
    revelationPlace: 'Mekke',
    bismillahPre: true,
    nameSimple: 'Fil Suresi',
    nameArabic: 'سُورَةُ الفِيل ',
    versesCount: 5,
    audioUrl: 'https://tevhidmeali.com/assets/mp3/ar/sure/abdussamed/105.mp3',
  },
  {
    id: 106,
    revelationPlace: 'Mekke',
    bismillahPre: true,
    nameSimple: 'Kureyş Suresi',
    nameArabic: 'سُورَةُ القُرَيش ',
    versesCount: 4,
    audioUrl: 'https://tevhidmeali.com/assets/mp3/ar/sure/abdussamed/106.mp3',
  },
  {
    id: 107,
    revelationPlace: 'Mekke',
    bismillahPre: true,
    nameSimple: 'Mâ’ûn Suresi',
    nameArabic: 'سُورَةُ المَاعون ',
    versesCount: 7,
    audioUrl: 'https://tevhidmeali.com/assets/mp3/ar/sure/abdussamed/107.mp3',
  },
  {
    id: 108,
    revelationPlace: 'Mekke',
    bismillahPre: true,
    nameSimple: 'Kevser Suresi',
    nameArabic: 'سُورَةُ الكَوثَر',
    versesCount: 3,
    audioUrl: 'https://tevhidmeali.com/assets/mp3/ar/sure/abdussamed/108.mp3',
  },
  {
    id: 109,
    revelationPlace: 'Mekke',
    bismillahPre: true,
    nameSimple: 'Kâfirûn Suresi',
    nameArabic: 'سُورَةُ الكافِرون ',
    versesCount: 6,
    audioUrl: 'https://tevhidmeali.com/assets/mp3/ar/sure/abdussamed/109.mp3',
  },
  {
    id: 110,
    revelationPlace: 'Medeni',
    bismillahPre: true,
    nameSimple: 'Nasr Suresi',
    nameArabic: 'سُورَةُ النّصر ',
    versesCount: 3,
    audioUrl: 'https://tevhidmeali.com/assets/mp3/ar/sure/abdussamed/110.mp3',
  },
  {
    id: 111,
    revelationPlace: 'Mekke',
    bismillahPre: true,
    nameSimple: 'Tebbet Suresi',
    nameArabic: 'سُورَةُ لهب / المَسَد ',
    versesCount: 5,
    audioUrl: 'https://tevhidmeali.com/assets/mp3/ar/sure/abdussamed/111.mp3',
  },
  {
    id: 112,
    revelationPlace: 'Mekke',
    bismillahPre: true,
    nameSimple: 'İhlâs Suresi',
    nameArabic: ' سُورَةُ الإخلاص',
    versesCount: 4,
    audioUrl: 'https://tevhidmeali.com/assets/mp3/ar/sure/abdussamed/112.mp3',
  },
  {
    id: 113,
    revelationPlace: 'Medeni',
    bismillahPre: true,
    nameSimple: 'Felâk Suresi',
    nameArabic: ' سُورَةُ الفَلَق ',
    versesCount: 5,
    audioUrl: 'https://tevhidmeali.com/assets/mp3/ar/sure/abdussamed/113.mp3',
  },
  {
    id: 114,
    revelationPlace: 'Medeni',
    bismillahPre: true,
    nameSimple: 'Nâs Suresi',
    nameArabic: 'سُورَةُ النَّاس ',
    versesCount: 6,
    audioUrl: 'https://tevhidmeali.com/assets/mp3/ar/sure/abdussamed/114.mp3',
  },
];
</script>

<template>
  <Search />
  <div class="container my-6 sm:my-16">
    <div class="mb-6 text-center text-lg font-semibold sm:text-2xl">Sure</div>
    <div class="grid gap-5 sm:grid-cols-2 lg:grid-cols-3">
      <SurahCard
        v-for="surah in surahList"
        :key="surah.id"
        :data="surah"
        @click="$router.push(`/${surah.id}?verse=1`)"
      />
    </div>
  </div>
</template>
